### DISCUSSION TITLE
Specific dependencies versions / pyproject file

### DISCUSSION THREAD

**Discussion by Mutestock** [Comfy-Org/ComfyUI#159] [General]
Torchvision / Torchaudio depends on torch 2.0.0 if you install them without specifying dependency versions. Here's a pyproject.toml file I made with poetry which you can use in case you run into this issue or something similar (Nvidia). 

```toml
[tool.poetry]
name = "comfyui"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "1.13.1"
xformers = "^0.0.16"
torchaudio = "0.13.1"
torchvision = "0.14.1"
torchdiffeq = "^0.2.3"
torchsde = "^0.2.5"
einops = "^0.6.0"
open-clip-torch = "^2.16.0"
transformers = "^4.27.1"
safetensors = "^0.3.0"
pytorch-lightning = "^2.0.0"
aiohttp = "^3.8.4"
accelerate = "^0.17.1"
pyyaml = "^6.0"
triton = "^2.0.0.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Usage:
1. make pyproject.toml file in the cloned project's root directory and copy contents above to the file.
2. use python 3.10 (alternatively try changing out the python version in the file. may or may not work out for you)
3. install poetry https://python-poetry.org/docs/#installation
4. > poetry shell
5. > poetry update
6. > python main.py

This has the added benefit of encapsulating the project's dependencies.
