### DISCUSSION TITLE
How to share model folders, between ComfyUI Krita to ComfyUI Standalone?

### DISCUSSION THREAD

**Discussion by SyamsQ** [Comfy-Org/ComfyUI#3766] [Q&A]
How to share model folders, between ComfyUI Krita and ComfyUI Standalone?

I have changed the folder path in extra_model_paths.yaml, but no models are added.

Please help, anyway thanks
![image](https://github.com/comfyanonymous/ComfyUI/assets/17028491/226787c1-b79b-4d6c-a3b5-68d854ebb9f4)
![image](https://github.com/comfyanonymous/ComfyUI/assets/17028491/1b3769f3-05f6-4b50-a9cb-11e6408526d2)

**Comment by BrechtCorbeel** [comment]
There's an environment variables file in there somewhere with all the specified paths that it pulls models from.

**Reply by TwoPintOhh** [reply]
There is file in the comfy folder for extra paths, just take the .example file extension away and edit the file as needed

**Comment by MohammadAboulEla** [comment]
just google for or ask chat gpt "how to create a symbolic folder"

**Reply by ltdrdata** [reply]
Don't use symbolic folder. This is the main reason of the updating failure.

**Comment by KosmiKFead** [comment]
I know the answer! and im really not a pro or anything so i might still be wrong but its working so far (A new trick i learned)

Get junction magic and install it (you wont regret it, you need it for a TON of disk saving and folder sharing scenarios). 

Close everything and MOVE whatever folders like checkpoints, loras etc... you want to share between auto1111 and confyui to a folder like "Shared modules" or something you like.

Select all the moved folders, right click and select "pick source"...

Browse to where you cut these things from originally and right-click on the window title or in the window (not on a folder) 

From the menu select "drop as junction".. DONE... now the file system will tell comfy ui the folders are there (but they aren't, those junctions will fool any app to use your junctions instead!

**Reply by Woisek** [reply]
Making junctions isn't new and making them even less. No tools required for that.

**Comment by Maevertigo** [comment]
> How to share model folders, between ComfyUI Krita and ComfyUI Standalone?
> 
> I have changed the folder path in extra_model_paths.yaml, but no models are added.
> 
> Please help, anyway thanks ![image](https://private-user-images.githubusercontent.com/17028491/340430908-226787c1-b79b-4d6c-a3b5-68d854ebb9f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDY0NTgsIm5iZiI6MTcyNzg0NjE1OCwicGF0aCI6Ii8xNzAyODQ5MS8zNDA0MzA5MDgtMjI2Nzg3YzEtYjc5Yi00ZDZjLWEzYjUtNjhkODU0ZWJiOWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA1MTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlN2YxZWYxMTcwOTJkMjY0MWU4MDBlMjVmNDg5MzFjZDVkOGJmMGE0YTkzZTI5NTU4YzcxMjYwODgwOGQzZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oLfky2xUWHrTT5E3dD9DL7WzxI-8IXMhZsuC1LMK7bY) ![image](https://private-user-images.githubusercontent.com/17028491/340430932-1b3769f3-05f6-4b50-a9cb-11e6408526d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDY0NTgsIm5iZiI6MTcyNzg0NjE1OCwicGF0aCI6Ii8xNzAyODQ5MS8zNDA0MzA5MzItMWIzNzY5ZjMtMDVmNi00YjUwLWE5Y2ItMTFlNjQwODUyNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA1MTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzODY4OTU4MzY2YmUzNjM5MGVkNDg1YTRhYmUzYmUwYWIwNDA5MTkyMzg2ZmM2ZmYxM2IxMWY4NTdiZWI3NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eW_suIySPxtPataCjlInzkMtu-vm7VCW2zy4PECj0Fo)

Edit your extra_model_paths.yaml file in krita by uncommenting the lines you need.
example:
```
#Rename this to extra_model_paths.yaml and ComfyUI will load it


#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: path/to/stable-diffusion-webui/

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet

#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

comfyui:
     base_path: D://ComfyUI_windows_portable//ComfyUI
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
#     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
```
