### DISCUSSION TITLE
Boosting ComfyUI Model Load Speed in Google Colab Pro with Google Drive

### DISCUSSION THREAD

**Discussion by Amit30swgoh** [Comfy-Org/ComfyUI#4909] [Ideas]
@comfyanonymous friend, if I want to speed up loading models in ComfyUI that are stored in my mounted Google Drive, for example, 
```
/content/drive/MyDrive/ComfyUI/models/checkpoints/Juggernaut-XI-byRunDiffusion.safetensors,
 can I simply edit my extra_model_paths.yaml file like this? 
# Config for ComfyUI
comfyui:
    base_path: /content/comfyui/   # Local base path for ComfyUI
    checkpoints: /content/checkpoints/   # Local path for frequently used models
    clip: /content/drive/MyDrive/ComfyUI/models/clip/
    clip_vision: /content/drive/MyDrive/ComfyUI/models/clip_vision/
    configs: /content/drive/MyDrive/ComfyUI/models/configs/
    controlnet: /content/drive/MyDrive/ComfyUI/models/controlnet/
    embeddings: /content/drive/MyDrive/ComfyUI/models/embeddings/
    loras: /content/drive/MyDrive/ComfyUI/models/loras/
    upscale_models: /content/drive/MyDrive/ComfyUI/models/upscale_models/
    vae: /content/drive/MyDrive/ComfyUI/models/vae/

# Optional other UI settings
other_ui:
    base_path: /content/drive/MyDrive/ComfyUI/other_ui/
    checkpoints: /content/drive/MyDrive/ComfyUI/models/checkpoints/
    gligen: /content/drive/MyDrive/ComfyUI/models/gligen/
    custom_nodes: /content/drive/MyDrive/ComfyUI/custom_nodes/
```
 

And then, copy the frequently used models to a local directory in my Colab Pro Python 3 Jupyter Notebook environment using the following code? 
```from google.colab import drive
drive.mount('/content/drive')

# Create local directories
!mkdir -p /content/checkpoints/
!mkdir -p /content/unet/FLUX1/

# Copy frequently used models to local directory
!cp /content/drive/MyDrive/ComfyUI/models/checkpoints/Juggernaut-XI-byRunDiffusion.safetensors /content/checkpoints/

!cp /content/drive/MyDrive/ComfyUI/models/unet/FLUX1/flux1-dev-Q8_0_11.84GB.gguf /content/unet/FLUX1/
!cp /content/drive/MyDrive/ComfyUI/models/unet/FLUX1/flux1-dev-fp8_11.08GB.safetensors /content/unet/FLUX1/
!cp /content/drive/MyDrive/ComfyUI/models/unet/FLUX1/t5-v1_1-xxl-encoder-Q8_0_4.71GB.gguf /content/unet/FLUX1/
!cp /content/drive/MyDrive/ComfyUI/models/unet/FLUX1/t5-v1_1-xxl-encoder-f16_8.87GB.gguf /content/unet/FLUX1/

**Comment by ltdrdata** [comment]
if you will copy to /content like this:
```
!mkdir -p /content/checkpoints/
!mkdir -p /content/unet/FLUX1/
```

You have to set like this:

```
comfyui:
    base_path: /content
    checkpoints: checkpoints
    diffusion_models: unet
```
